[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

[rpc_endpoints]
arbitrum-sepolia = "${ARB_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
